apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: dev
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
      nodePort: 32017  # Must be in the range 30000-32767
  type: NodePort
