version: "3.9"
services:
  # lyxa_backend:
  #   image:  lyxa_backend_image
  #   container_name: lyxa_backend_container
  #   build:
  #     context: ../
  #     dockerfile: Dockerfile
  #   ports:
  #     - 4000:4000        
  #   networks:
  #     lyxa_network:
  #       ipv4_address: 192.168.2.3 
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: test
    networks:
      lyxa_network:
        ipv4_address: 192.168.2.4

volumes:
  mongodb_data:
    driver: local
  
networks:
  lyxa_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24
          gateway: 192.168.2.1