apiVersion: v1
kind: Service
metadata:
  name: lyxa-backend-service
  namespace: dev
spec:
  selector:
    app: lyxa-backend
  ports:
    - protocol: TCP
      port: 1002
      targetPort: 2312
      nodePort: 32016
  type: NodePort